site_name: UnixSoft-BASIC Reference
site_url: https://theexiledcat.github.io/UnixSoft-Basic/
use_directory_urls: false
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Guide: guide.md
  - USB Reference: USB.md
theme: 
  name: material
  palette: 
    scheme: slate
  features:
    - toc.integrate 
    - toc.follow
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: table
  - pymdownx.superfences
  - admonition
  - pymdownx.snippets